reverting back to brew

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,35 +1,77 @@
 #!/bin/bash
+set -e
 
-# Install nix package manager
-curl -L https://nixos.org/nix/install | sh
+trap 'catch' ERR
+catch() {
+	echo "Bootstrapping failed!"
+	kill $!
+}
 
-# source nix path
-. /home/bernt/.nix-profile/etc/profile.d/nix.sh
+trap cleanUp SIGHUP SIGINT SIGTERM
+cleanUp() {
+	echo "cleaning up"
+}
 
-# Install packages
-nix-env -i \
-	zsh \
-	kitty \
-	git \
-	curl \
-	unzip \
-	azure-cli \
-	k9s \
-	kubectl \
-	kubectx \
-	lazygit \
-	ripgrep \
-	wget \
-	tmux \
-	oh-my-zsh \
-	neovim \
-	zsh-syntax-highlighting \
-	zsh-autosuggestions \
-	pure-prompt
+OS="$(uname -s)"
+if [ "${OS}" == "Linux" ]; then
+	DISTRO_ID=$(lsb_release -is)
+fi
 
-# zsh default shell
+SUPPORTED_DEBIAN_ID=("Pop Ubuntu Debian")
+SUPPORTED_REDHAT_ID=("Fedora")
+
+linuxInstall() {
+
+	if [[ " ${SUPPORTED_DEBIAN_ID[*]} " =~ ${DISTRO_ID} ]]; then
+		sudo apt-get install build-essential procps curl file git -y
+		sudo apt-get install kitty -y
+	elif
+		[[ " ${SUPPORTED_REDHAT_ID[*]} " =~ ${DISTRO_ID} ]]
+	then
+		sudo dnf installl groupinstall 'Development Tools'
+		sudo dnf install kitty
+	else
+		echo"Linux distro $DISTRO_ID not supported!"
+		exit 1
+	fi
+
+	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+
+	brew bundle --file "$(dirname "$0")/Brewfile"
+
+	wget -O /tmp/Hack.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
+	unzip -o /tmp/Hack.zip -d "$HOME/.local/share/fonts"
+	fc-cache -fv
+}
+
+macOsInstall() {
+
+	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+	brew bundle --file "$(dirname "$0")/Brewfile"
+	brew install kitty
+	brew install font-hack-nerd-font
+}
+
+if [ "$OS" == "Darwin" ]; then
+	macOsInstall
+elif [ "$OS" == "Linux" ]; then
+	linuxInstall
+else
+	echo "No OS supported"
+	exit 1
+fi
+
+volta install node@lts
+
+sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc --unattended
+
 zsh_path=$(which zsh)
 if ! grep -q "^${zsh_path}$" "/etc/shells"; then
 	echo "$zsh_path" | sudo tee -a /etc/shells
 fi
-chsh -s "${zsh_path}" "${USER}"
+
+sudo -S chsh -s "$zsh_path" "${USER}"
+
+echo "Done."
+exit 0
